server:
  port: 8084
  servlet:
    context-path: /
swagger:
  enabled: true
  title: WordAnalysis 系统 Jieba服务测试
  contact:
    name: WordAnalysis-JiebaService地址
    url: https://gitee.com/Erichan/EngineerCMS-JiebaService
  base-package: com.wordanalysis.jiebaservice

spring:
  application:
    name: WordAnalysis-JiebaService
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      registerWithEureka: false
      fetchRegistry: false
  instance:
    instance-id: jieba-service
    prefer-ip-address: true     #访问路径可以显示IP地址
